blank_issues_enabled: false

contact_links:
  - name: Discussions
    url: https://github.com/oopooa/opresume/discussions
    about: Got questions, ideas to share, or a cool resume template to show off? Come say hi in Discussions!
