/**
 * 精选高校品牌库（自动生成：tools/school_brand.py --list ... --ts ...）
 * 数据来源：维基百科/维基共享（校徽文件直链）+ 本地主色提取。
 * 仅作简历预览用途；商用发布前请自行确认目标高校校徽的使用授权。
 */
import type { SchoolBrand } from './campus-brands';

export const BRAND_DB: Record<string, SchoolBrand> = {
  "清华大学": { logoUrl: "/school-logos/tsinghua-logo.jpg", color: "#660874" },
  "北京大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Peking_University_logo_%281917%29.jpg", color: "#990000" },
  "复旦大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/44/Fudan_University_Logo.svg", color: "#0E42A0" },
  "上海交通大学": { logoUrl: "", color: "#A9021F" },
  "浙江大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/1/12/%E6%B5%99%E6%B1%9F%E5%A4%A7%E5%AD%A6%E5%9B%BD%E9%99%85%E8%81%94%E5%90%88%E5%AD%A6%E9%99%A2logo.png", color: "#003F88" },
  "南京大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/f/fb/%E5%8D%97%E4%BA%AC%E5%A4%A7%E5%AD%A6%E6%A0%A1%E5%BE%BD.svg", color: "#6B0060" },
  "中国科学技术大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/en/3/3c/Logo_of_University_of_Science_and_Technology_of_China.svg", color: "#034FA4" },
  "哈尔滨工业大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/4/46/Harbin_Institute_of_Technology_logo.svg", color: "#A9021F" },
  "西安交通大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9f/%E8%A5%BF%E5%AE%89%E4%BA%A4%E9%80%9A%E5%A4%A7%E5%AD%A6%E6%89%8B%E8%AF%AD%E7%A4%BE%E7%A4%BE%E5%BE%BD.PNG", color: "#E06277" },
  "武汉大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/d/d3/%E6%AD%A6%E6%B1%89%E5%A4%A7%E5%AD%A6%E5%8F%A3%E8%85%94%E5%8C%BB%E5%AD%A6%E9%99%A2.jpg", color: "#B74C49" },
  "华中科技大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/en/0/01/Huazhong_University_of_Science_and_Technology_logo.png", color: "#155FA4" },
  "中山大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fd/%E4%B8%AD%E5%B1%B1%E5%A4%A7%E5%AD%A6%E5%8D%97%E6%A0%A1%E5%9B%AD_-_%E6%A0%A1%E5%BE%BD_-_2026-05-12_02.jpg", color: "#658229" },
  "四川大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/en/5/53/Sichuan_University_Logo.svg", color: "#A9021F" },
  "山东大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/9/9c/%E5%B1%B1%E4%B8%9C%E5%A4%A7%E5%AD%A6%E9%99%84%E5%B1%9E%E4%B8%AD%E5%AD%A6%E6%A0%A1%E5%BE%BD.jpg", color: "#4EBBF3" },
  "东南大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/0/07/%E4%B8%9C%E5%8D%97%E5%A4%A7%E5%AD%A6logo.svg", color: "#A9021F" },
  "同济大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Tongji_huabiao.jpg/500px-Tongji_huabiao.jpg", color: "#1D3D7A" },
  "天津大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/7/7f/Tianjin_University_logo.svg", color: "#A9021F" },
  "南开大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a5/Nankai_University_logo.svg/500px-Nankai_University_logo.svg.png", color: "#721A60" },
  "北京航空航天大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/a/a6/Beihang_University_Logo.svg", color: "#01529B" },
  "北京理工大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/9/92/Beijing_Institute_of_Technology_Logo.svg", color: "#136E40" },
  "北京师范大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/8/87/Beijing_Normal_University_logo.svg", color: "#A9021F" },
  "中国人民大学": { logoUrl: "", color: "#A9021F" },
  "厦门大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/commons/7/75/Xiamen_University_logo.svg", color: "#122E67" },
  "吉林大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/d/d3/%E5%90%89%E6%9E%97%E5%A4%A7%E5%AD%A6%E7%8F%A0%E6%B5%B7%E5%AD%A6%E9%99%A2%E6%A0%A1%E5%BE%BD.jpg", color: "#E49F90" },
  "中南大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/c/c9/%E4%B8%AD%E5%8D%97%E5%A4%A7%E5%AD%A6%E6%9C%BA%E7%94%B5%E5%B7%A5%E7%A8%8B%E5%AD%A6%E9%99%A2%E9%99%A2%E5%BE%BD.jpg", color: "#D7AD38" },
  "湖南大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/a/ad/Hunan_University_Logo_2020.svg", color: "#A9021F" },
  "大连理工大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/8/83/%E5%A4%A7%E8%BF%9E%E7%90%86%E5%B7%A5%E5%A4%A7%E5%AD%A6%E9%99%84%E5%B1%9E%E9%AB%98%E4%B8%AD%E6%A0%A1%E5%BE%BD.png", color: "#2F60AF" },
  "重庆大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/7/74/Chongqing_University_logo.svg", color: "#A9021F" },
  "兰州大学": { logoUrl: "", color: "#A9021F" },
  "东北大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/f/f4/Northeastern_University_%28China%29_logo.svg", color: "#A9021F" },
  "华东师范大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/7/71/%E5%8D%8E%E4%B8%9C%E5%B8%88%E8%8C%83%E5%A4%A7%E5%AD%A6%E6%A0%A1%E5%BE%BD.jpg", color: "#897D53" },
  "华东理工大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/commons/1/19/East_China_University_of_Science_and_Technology_Text_Logo_in_English.svg", color: "#A9021F" },
  "上海财经大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/4/4d/Shanghai_University_of_Finance_and_Economics_logo.jpg", color: "#AD797C" },
  "中央财经大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/d/dd/Central_University_of_Finance_and_Economics_logo.svg", color: "#A9021F" },
  "对外经济贸易大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/en/9/95/University_of_International_Business_and_Economics_LOGO.png", color: "#13579F" },
  "电子科技大学": { logoUrl: "", color: "#A9021F" },
  "西北工业大学": { logoUrl: "", color: "#A9021F" },
  "华南理工大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/d/d5/South_China_University_of_Technology_Logo_%282006-2022%29.svg", color: "#A9021F" },
  "北京邮电大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/b/bb/Emblem_of_Beijing_University_of_Posts_and_Telecommunications.svg", color: "#A9021F" },
  "北京交通大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/en/9/98/Beijing_Jiaotong_University.png", color: "#A9021F" },
  "北京科技大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/a/a5/University_of_Science_and_Technology_Beijing_logo.svg", color: "#A9021F" },
  "南京航空航天大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/2/2b/Nanjing_University_of_Aeronautics_and_Astronautics.svg", color: "#A9021F" },
  "南京理工大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Time_Square_in_Nanjing_University_of_Science_and_Technology_2012-05.JPG/500px-Time_Square_in_Nanjing_University_of_Science_and_Technology_2012-05.JPG", color: "#D3E2F2" },
  "河海大学": { logoUrl: "", color: "#A9021F" },
  "江南大学": { logoUrl: "", color: "#A9021F" },
  "中国矿业大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/en/8/82/China_University_of_Mining_and_Technology_logo.png", color: "#2C4673" },
  "中国地质大学(武汉)": { logoUrl: "", color: "#A9021F" },
  "中国石油大学(华东)": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/d/d5/China_University_Of_Petroleum_badge.svg", color: "#A9021F" },
  "中国海洋大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/%E4%B8%AD%E5%9B%BD%E6%B5%B7%E6%B4%8B%E5%A4%A7%E5%AD%A6%E6%B5%B7%E6%B4%8B%E7%A7%91%E6%8A%80%E4%B8%AD%E5%BF%83%E6%A5%BC%E5%8F%8A%E6%95%99%E5%AD%A6%E6%A5%BC.jpg/500px-%E4%B8%AD%E5%9B%BD%E6%B5%B7%E6%B4%8B%E5%A4%A7%E5%AD%A6%E6%B5%B7%E6%B4%8B%E7%A7%91%E6%8A%80%E4%B8%AD%E5%BF%83%E6%A5%BC%E5%8F%8A%E6%95%99%E5%AD%A6%E6%A5%BC.jpg", color: "#BCC9D4" },
  "西北大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Northwest_University_Name.svg", color: "#A9021F" },
  "郑州大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/2/27/First_Affiliated_Hospital_of_Zhengzhou_University_logo.svg", color: "#A9021F" },
  "苏州大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/3/39/%E8%8B%8F%E5%B7%9E%E5%A4%A7%E5%AD%A6%E5%BA%94%E7%94%A8%E6%8A%80%E6%9C%AF%E5%AD%A6%E9%99%A2%E6%A0%A1%E5%BE%BD.png", color: "#DD211E" },
  "暨南大学": { logoUrl: "", color: "#A9021F" },
  "深圳大学": { logoUrl: "", color: "#A9021F" },
  "上海大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/en/9/90/Shanghai_University_of_Finance_and_Economics_logo.png", color: "#DE0B0D" },
  "西南大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/0/03/Logo_of_Southwest_University_for_Nationalities.svg", color: "#A9021F" },
  "华中师范大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4f/CCNU_Logo.svg/500px-CCNU_Logo.svg.png", color: "#007683" },
  "陕西师范大学": { logoUrl: "", color: "#A9021F" },
  "西南交通大学": { logoUrl: "", color: "#A9021F" },
  "长安大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/5/5e/Chang%27an_University_Emblem.svg", color: "#A9021F" },
  "太原理工大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/3/33/Taiyuan_University_of_Technology_Logo.svg", color: "#A9021F" },
  "辽宁大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/1/14/Liaoning_University_logo.png", color: "#2599B5" },
  "东北师范大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/9/93/Northeast_Normal_University_logo.svg", color: "#A9021F" },
  "哈尔滨工程大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/2/27/Harbin_Engineering_University_logo.svg", color: "#A9021F" },
  "东华大学": { logoUrl: "/school-logos/dhu-logo.png", color: "#A9021F" },
  "北京工业大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/a/ac/Beijing_University_of_Technology.svg", color: "#A9021F" },
  "浙江工业大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/20250423_Zhejiang_Gongye_Daxue.jpg/500px-20250423_Zhejiang_Gongye_Daxue.jpg", color: "#8CA3C1" },
  "南京师范大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/c/c1/Nanjing_Normal_University.svg", color: "#A9021F" },
  "福建师范大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/e/e9/Fujian_Normal_University_logo.svg", color: "#A9021F" },
  "南昌大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/d/df/Nanchang_University_Logo.svg", color: "#A9021F" },
  "云南大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/c/ca/Yunnan_University_logo.svg", color: "#A9021F" },
  "广西大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/5/57/Guangxi_University_logo.jpg", color: "#E1767B" },
  "贵州大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/9/99/Guizhou_University_Logo.png", color: "#B50303" },
  "海南大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/9/95/Hainan_University_logo.png", color: "#5880AD" },
  "内蒙古大学": { logoUrl: "", color: "#A9021F" },
  "新疆大学": { logoUrl: "", color: "#A9021F" },
  "宁夏大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/7/7a/Ningxia_University.svg", color: "#A9021F" },
  "青海大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/f/f9/Qinghai_University_Medical_College_Logo.jpg", color: "#6F7BA5" },
  "天津工业大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/3/30/Tiangong_University_Emblem.svg", color: "#A9021F" },
  "武汉理工大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/6/6e/Wuhan_University_of_Technology_logo.svg", color: "#2962A8" },
  "南京工业大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/5/5f/Nanjing_Tech_University_Emblem.svg", color: "#A9021F" },
  "杭州电子科技大学": { logoUrl: "", color: "#A9021F" },
  "南京邮电大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/en/e/e1/Nanjing_University_of_Posts_and_Telecommunications_logo.png", color: "#29469D" },
  "东北财经大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/9/9a/Dongbei_University_of_Finance_and_Economics.jpg", color: "#859AB8" },
  "首都经济贸易大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/2/28/Capital_University_of_Economics_and_Business_logo.png", color: "#A9021F" },
  "西安电子科技大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/8/83/Xidian_University_Logo.svg", color: "#A9021F" },
  "华东政法大学": { logoUrl: "", color: "#A9021F" },
  "西南政法大学": { logoUrl: "", color: "#A9021F" },
  "中国政法大学": { logoUrl: "", color: "#A9021F" },
  "上海外国语大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/0/06/Shanghai_International_Studies_University_logo.svg", color: "#A9021F" },
  "北京外国语大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/commons/0/07/%E5%8C%97%E4%BA%AC%E5%A4%96%E5%9B%BD%E8%AF%AD%E5%A4%A7%E5%AD%A6.jpeg", color: "#71679B" },
  "燕山大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/1/15/Yanshan_University_logo.svg", color: "#A9021F" },
  "华南师范大学": { logoUrl: "", color: "#A9021F" },
  "宁波大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/a/af/Ningbo_University_Emblem.svg", color: "#A9021F" },
  "河南大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/7/74/Henan_University_Logo_2022.png", color: "#6F81B6" },
  "安徽大学": { logoUrl: "https://upload.wikimedia.org/wikipedia/zh/6/6a/Anhui_University_Logo.svg", color: "#A9021F" },
  "哈尔滨工业大学(深圳)": { logoUrl: "", color: "#A9021F" },
};

/** 高校英文别名（用于维基百科英文站检索校徽） */
export const BRAND_ALIASES: Record<string, string> = {
  "清华大学": "Tsinghua University",
  "北京大学": "Peking University",
  "复旦大学": "Fudan University",
  "上海交通大学": "Shanghai Jiao Tong University",
  "浙江大学": "Zhejiang University",
  "南京大学": "Nanjing University",
  "中国科学技术大学": "University of Science and Technology of China",
  "哈尔滨工业大学": "Harbin Institute of Technology",
  "西安交通大学": "Xi'an Jiaotong University",
  "武汉大学": "Wuhan University",
  "华中科技大学": "Huazhong University of Science and Technology",
  "中山大学": "Sun Yat-sen University",
  "四川大学": "Sichuan University",
  "山东大学": "Shandong University",
  "东南大学": "Southeast University",
  "同济大学": "Tongji University",
  "天津大学": "Tianjin University",
  "南开大学": "Nankai University",
  "北京航空航天大学": "Beihang University",
  "北京理工大学": "Beijing Institute of Technology",
  "北京师范大学": "Beijing Normal University",
  "中国人民大学": "Renmin University of China",
  "厦门大学": "Xiamen University",
  "吉林大学": "Jilin University",
  "中南大学": "Central South University",
  "湖南大学": "Hunan University",
  "大连理工大学": "Dalian University of Technology",
  "重庆大学": "Chongqing University",
  "兰州大学": "Lanzhou University",
  "东北大学": "Northeastern University",
  "华东师范大学": "East China Normal University",
  "华东理工大学": "East China University of Science and Technology",
  "上海财经大学": "Shanghai University of Finance and Economics",
  "中央财经大学": "Central University of Finance and Economics",
  "对外经济贸易大学": "University of International Business and Economics",
  "电子科技大学": "University of Electronic Science and Technology of China",
  "西北工业大学": "Northwestern Polytechnical University",
  "华南理工大学": "South China University of Technology",
  "北京邮电大学": "Beijing University of Posts and Telecommunications",
  "北京交通大学": "Beijing Jiaotong University",
  "北京科技大学": "University of Science and Technology Beijing",
  "南京航空航天大学": "Nanjing University of Aeronautics and Astronautics",
  "南京理工大学": "Nanjing University of Science and Technology",
  "河海大学": "Hohai University",
  "江南大学": "Jiangnan University",
  "中国矿业大学": "China University of Mining and Technology",
  "中国地质大学(武汉)": "China University of Geosciences",
  "中国石油大学(华东)": "China University of Petroleum",
  "中国海洋大学": "Ocean University of China",
  "西北大学": "Northwest University",
  "郑州大学": "Zhengzhou University",
  "苏州大学": "Soochow University",
  "暨南大学": "Jinan University",
  "深圳大学": "Shenzhen University",
  "上海大学": "Shanghai University",
  "西南大学": "Southwest University",
  "华中师范大学": "Central China Normal University",
  "陕西师范大学": "Shaanxi Normal University",
  "西南交通大学": "Southwest Jiaotong University",
  "长安大学": "Chang'an University",
  "太原理工大学": "Taiyuan University of Technology",
  "辽宁大学": "Liaoning University",
  "东北师范大学": "Northeast Normal University",
  "哈尔滨工程大学": "Harbin Engineering University",
  "东华大学": "Donghua University",
  "北京工业大学": "Beijing University of Technology",
  "浙江工业大学": "Zhejiang University of Technology",
  "南京师范大学": "Nanjing Normal University",
  "福建师范大学": "Fujian Normal University",
  "南昌大学": "Nanchang University",
  "云南大学": "Yunnan University",
  "广西大学": "Guangxi University",
  "贵州大学": "Guizhou University",
  "海南大学": "Hainan University",
  "内蒙古大学": "Inner Mongolia University",
  "新疆大学": "Xinjiang University",
  "宁夏大学": "Ningxia University",
  "青海大学": "Qinghai University",
  "天津工业大学": "Tiangong University",
  "武汉理工大学": "Wuhan University of Technology",
  "南京工业大学": "Nanjing Tech University",
  "杭州电子科技大学": "Hangzhou Dianzi University",
  "南京邮电大学": "Nanjing University of Posts and Telecommunications",
  "东北财经大学": "Dongbei University of Finance and Economics",
  "首都经济贸易大学": "Capital University of Economics and Business",
  "西安电子科技大学": "Xidian University",
  "华东政法大学": "East China University of Political Science and Law",
  "西南政法大学": "Southwest University of Political Science and Law",
  "中国政法大学": "China University of Political Science and Law",
  "上海外国语大学": "Shanghai International Studies University",
  "北京外国语大学": "Beijing Foreign Studies University",
  "燕山大学": "Yanshan University",
  "华南师范大学": "South China Normal University",
  "宁波大学": "Ningbo University",
  "河南大学": "Henan University",
  "安徽大学": "Anhui University",
  "哈尔滨工业大学(深圳)": "Harbin Institute of Technology Shenzhen",
};
